### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Reimajo**
- Corrected note about Quest URL resolver, VRChat has one of Quest now as well, added in a recent update
- Corrected links to prefabs (they have moved to the path of the package now). 

**IMPORTANT NOTE 1:** VRChat forgot to add the AVPro prefab to the menu and to the Udon example scene, otherwise it would be better to point users there.

**IMPORTANT NOTE 2:** Those prefabs break when adding them to a scene and must be manually corrected by the users, so asking the user to use udon prefabs is bad (prefabs and Udon doesn't go well together, they always lose their references). It would be better to have them in the example scene instead, unpacked, and ask the user to go there. Providing Udon Prefabs is bad practice. Tested by 2 independent users with the newest SDK.

### CODE REVIEW

**Comment by momo-the-monster** [comment]
Thanks for the video player updates, @Reimajo! I also tried testing the scenario you described, adding the UdonSyncPlayer prefab to a new scene and it worked for me, sorry to hear you've been having issues:

image

**Comment by Reimajo** [comment]
Thank you for testing! It broke in the previous SDK for both of us, but in the current one, it works again (just tested). But that is just the usual issue with prefabs, they lose Udon references in a scene sometimes. Two notes here regarding this change:
- The picture on the docs still shows the old path now, until today I had no idea I could add pictures here (will make another PR)
- The AVPro prefab is also missing in the Udon example scene and in the menu, but I cannot make a PR for this change

**Comment by Reimajo** [comment]
Previously (one SDK ago), you could access the samples from the main menu bar under "VRChatSDK->Samples". But there was only the regular player example as an entry listed, not the AVPro example. This entry was replaced in the current one.
VRChat changed its documentation, pointing users to the example scene now, where all samples are supposed to be (described at "finding the samples": https://vcc.docs.vrchat.com/guides/finding-the-samples/)
The problem is that (contrary to what this website says), the AVPro video player example cannot be found in this scene, so it should be added there IMHO. Those players are not set up in the same way and are not interchangeable. For live streaming, you need the AVPro player, and it has special components in its setup which aren't easy to understand, so having an example is great. It took us a while to find it because the VRChat website says that all samples should be in there, but are not.

**Comment by momo-the-monster** [comment]
Hm - the latest SDK still has these menu items:
image

**Comment by Reimajo** [comment]
Might be easier to understand the issue if I describe what I did:

- I tried finding the AVPro example setup
- I googled where the VRChat examples can be found nowadays
- I found this VRChat website: https://vcc.docs.vrchat.com/guides/finding-the-samples/
- It shows that you can find the examples in the Udon Example scene now
- I open this example scene, but cannot find the AVPro example in there, assuming it was removed

For the reasons described above, the AVPro example setup is more complex and cannot be explained by looking at the Unity video player example. It is also not feature-complete, so both are needed for different use cases. 

Suggestion: Add the AVPro to the example scene, or add a note to the "finding the samples" page that not all examples can be found that way

**Pull request merged**
